// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKLYvga_M7mrTsrOcbkhwQbbuNpnvaKAo',
    appId: '1:213816944993:web:4f35739c9eac88a1087d20',
    messagingSenderId: '213816944993',
    projectId: 'projectmobilep2',
    authDomain: 'projectmobilep2.firebaseapp.com',
    storageBucket: 'projectmobilep2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX9EsvhWEFd3vNscLD0NL8lzdXd68CsRo',
    appId: '1:213816944993:android:bdc69afcadbe1aeb087d20',
    messagingSenderId: '213816944993',
    projectId: 'projectmobilep2',
    storageBucket: 'projectmobilep2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9GFTdM3SzNYC1MIfvxtOII6BfKDLZGoI',
    appId: '1:213816944993:ios:f37cd940c0032923087d20',
    messagingSenderId: '213816944993',
    projectId: 'projectmobilep2',
    storageBucket: 'projectmobilep2.firebasestorage.app',
    iosBundleId: 'com.example.projectmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9GFTdM3SzNYC1MIfvxtOII6BfKDLZGoI',
    appId: '1:213816944993:ios:f37cd940c0032923087d20',
    messagingSenderId: '213816944993',
    projectId: 'projectmobilep2',
    storageBucket: 'projectmobilep2.firebasestorage.app',
    iosBundleId: 'com.example.projectmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKLYvga_M7mrTsrOcbkhwQbbuNpnvaKAo',
    appId: '1:213816944993:web:c0d2c515b6cb543a087d20',
    messagingSenderId: '213816944993',
    projectId: 'projectmobilep2',
    authDomain: 'projectmobilep2.firebaseapp.com',
    storageBucket: 'projectmobilep2.firebasestorage.app',
  );
}
